# -*- coding: utf-8 -*-
"""final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZeTpgh90fTH4bosqf2dGZhnjS0Hzl0_
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

#Step 1 : load the dataset
final=pd.read_csv(r"/content/drive/MyDrive/Heart_Disease_Prediction.csv")

print(final.head())

final.describe()

final.shape

final.info()

print(final.dtypes)

print(final.isnull().sum())

final.describe(include=['float64'])

#COnverting categorial values into numerical values
final['Heart Disease']=final['Heart Disease'].replace({'Presence':1,'Absence':0})
final1=final
print(final1)

#Fill missing values with the column mean (if there are any)
final1.fillna(final1.mean(),inplace=True)

final1 = final1.dropna()

final.head()

X = final.drop('Heart Disease', axis=1)  # Features
y = final['Heart Disease']





